### ISSUE TITLE
Options not listed in install-tool help [2.3.1-rc1 on Sourceforge]  

### ISSUE THREAD

**Issue by ohearnk** [OpenSpeedShop/openspeedshop#2]
Several of the --skip-*-build options are not listed when install-tool --help is invoked (e.g., --skip-sqlite-build, --skip-xercesc-build).  The logic is there in the script for these options, so this is an easy fix.

Also, there is not an option to skip building cmake.  There is no logic for this in the install-tool script, so this would involve a bit of work to add.

**Comment by jgalarowicz** [comment]
This is fixed in 2.3.1-rc2 on sourceforge.   Let me know if it works for you.   Thanks Jim G.

**Comment by ohearnk** [comment]
Thanks for the quick fix.  The options work on my system, including --skip-cmake-build when --build-compiler gnu is set.

However, if building CMake is enabled and --build-compiler intel is set, the CMake build does not use the Intel compilers but instead uses GCC.  On my machine, the Intel compilers are earlier in my shell search path than the GCC compilers.  So, I'm guessing this has something to do with bootstrapping for CMake.

**Comment by jgalarowicz** [comment]
I may not have added the Intel compiler for cmake support.  I can change 
that.
Jim G

**Comment by jgalarowicz** [comment]
If you don't want to wait, this might work in .support_for_install.sh at 
around line 2287
add the bold lines.   I think this should work.   I don't have an intel 
compiler available at the moment to test it.


    if [ $1 == 1 ] ; then
        export CMAKE_INSTALL_PATH=$CBTF_CMAKE_ROOT
    else
        export CMAKE_INSTALL_PATH=$KRELL_ROOT_PREFIX/cmake-$cmakever
        export KRELL_ROOT_CMAKE_ROOT=$KRELL_ROOT_PREFIX/cmake-$cmakever
    fi

*   if [ "$build_with_intel" = 1 ]; then**
**       cc="gcc" CC="icc" CXX="icpc" ./bootstrap 
--prefix=$CMAKE_INSTALL_PATH; make; make install**
**   else*
        cc="gcc" CC="gcc" CXX="g++" ./bootstrap 
--prefix=$CMAKE_INSTALL_PATH; make; make install
*   fi*

    popd

**Comment by jgalarowicz** [comment]
I just put 2.3.1.rc3 on sourceforge.  It has the above change in .support_for_install.sh.
There are other changes that I'm trying to get to another person for building on a Cray, so I put this fix in as well.
Jim G
